name: Build and publish containers

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write

concurrency:
  group: "build"
  cancel-in-progress: false

jobs:
  server:
    environment:
      name: ghcr
      url: ghcr.io/j-markiewicz/app-int-server:latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - run: cd server && docker build -t ghcr.io/j-markiewicz/app-int-server:latest .
      - run: docker push ghcr.io/j-markiewicz/app-int-server:latest
  website:
    environment:
      name: ghcr
      url: ghcr.io/j-markiewicz/app-int-website:latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - run: cd website && docker build -t ghcr.io/j-markiewicz/app-int-website:latest .
      - run: docker push ghcr.io/j-markiewicz/app-int-website:latest
